I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 46, in script call
    call MyRoom from _call_MyRoom
  File "game/script.rpy", line 236, in script
    $ lock_waxy = false
  File "game/script.rpy", line 236, in <module>
    $ lock_waxy = false
NameError: name 'false' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 46, in script call
    call MyRoom from _call_MyRoom
  File "game/script.rpy", line 236, in script
    $ lock_waxy = false
  File "/Applications/renpy-7.4.11-sdk/renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Applications/renpy-7.4.11-sdk/renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 236, in <module>
    $ lock_waxy = false
NameError: name 'false' is not defined

Darwin-23.6.0-x86_64-i386-64bit
Ren'Py 7.4.11.2266
After Hours at the Puzzle Museum 1.0
Wed Aug  7 19:37:43 2024
